app/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults

admin.site.index_title = "Django administration"
admin.site.name = "Django Admin"
admin.site.site_header = "Django administration"
admin.site.site_title = "Django site admin"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("allauth.urls")),
    path("", include("index.urls"), name="index"),
    path("decisions/", include("decisions.urls"), name="decisions"),
]

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))
    urlpatterns.extend(
        [
            path("__debug__/", include("debug_toolbar.urls")),
            path(
                "400/",
                defaults.bad_request,
                kwargs={"exception": Exception("Bad Request")},
            ),
            path(
                "403/",
                defaults.permission_denied,
                kwargs={"exception": Exception("Permission Denied")},
            ),
            path(
                "404/",
                defaults.page_not_found,
                kwargs={"exception": Exception("Not Found")},
            ),
            path("500/", defaults.server_error),
        ],
    )

app/decisions/urls.py
from django.urls import path

from . import views

app_name = "decisions"

urlpatterns = [
    path("", view=views.DecisionListView.as_view(), name="list"),
    path("results/", view=views.DecisionResultsView.as_view(), name="results"),
    path("<int:pk>/", views.DecisionDetailView.as_view(), name="detail"),
]

app/index/urls.py
from django.urls import path

from . import views

app_name = "index"

urlpatterns = [
    path("", view=views.IndexView.as_view(), name="index"),
]

app/decisions/models.py
from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.search import SearchVector, SearchVectorField
from django.db import models

OUTCOMES = [
    ("granted", "granted"),
    ("denied", "denied"),
    ("remanded", "remanded"),
]


class URL(models.Model):
    loc = models.CharField(max_length=128, unique=True)
    lastmod = models.CharField(max_length=10)

    def __str__(self) -> str:
        return self.loc


class Decision(models.Model):
    text = models.TextField()
    vector = SearchVectorField(null=True)
    citation = models.CharField(max_length=128, null=True, blank=True)
    date = models.CharField(max_length=10, null=True, blank=True)
    docket = models.CharField(max_length=128, null=True, blank=True)
    judge = models.CharField(max_length=128, null=True, blank=True)
    summary = models.TextField(null=True, blank=True)
    url = models.ForeignKey(URL, on_delete=models.CASCADE)

    class Meta:
        indexes = [
            GinIndex(fields=["vector"]),
        ]

    def __str__(self) -> str:
        return f"{self.text[:100]}..."

    def save(self, *args, **kwargs):
        self.vector = SearchVector("text")
        super().save(*args, **kwargs)


class Condition(models.Model):
    name = models.CharField(max_length=1024)
    outcome = models.CharField(max_length=10, choices=OUTCOMES, null=True, blank=True)
    reason = models.TextField(null=True, blank=True)
    decision = models.ForeignKey(Decision, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"{self.name} > {self.outcome}"

app/tasks/models.py
from django.db import models
from django.utils import timezone


class Task(models.Model):
    name = models.CharField(max_length=64, editable=False)
    datetime = models.DateTimeField(default=timezone.now)
    success = models.BooleanField(default=False)

    def __str__(self):
        return f"[{self.datetime.strftime('%Y-%M-%d %H:%M:%S')}] {'SUCCESS' if self.success else 'ERROR'} {self.name}"

app/users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

app/decisions/views.py
from django.views.generic import DetailView, ListView
from django.contrib.postgres.search import SearchHeadline, SearchQuery, SearchRank
from django.db.models import F

from decisions.models import Decision


class DecisionDetailView(DetailView):
    template_name = "decisions/detail.html"
    model = Decision
    context_object_name = "decision"


class DecisionListView(ListView):
    template_name = "decisions/list.html"
    model = Decision
    context_object_name = "decisions"
    paginate_by = 50
    ordering = "-date"


class DecisionResultsView(ListView):
    template_name = "decisions/list.html"
    model = Decision
    context_object_name = "decisions"
    paginate_by = 50

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["q"] = self.request.GET.get("q", "")
        return context

    def get_queryset(self):
        q = self.request.GET.get("q", "")
        query = SearchQuery(
            value=q,
            search_type="websearch",
        )
        headline = SearchHeadline(
            expression=F("text"),
            query=query,
            start_sel="<mark>",
            stop_sel="</mark>",
        )
        return (
            Decision.objects
            .annotate(rank=SearchRank(F("vector"), query))  # use precomputed vector field
            .annotate(headline=headline)
            .filter(rank__gte=0.001)
            .order_by("-rank")
        )

app/index/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = "index/index.html"

app/decisions/templates/decisions/base.html
{% extends "base.html" %}

app/decisions/templates/decisions/detail.html
{% extends "decisions/base.html" %}

{% block title %}Decision{% endblock %}

{% block content %}
  <div class="container">
    <div class="my-5">
      {{ decision.text|linebreaks }}
    </div>
  </div>
{% endblock %}

app/decisions/templates/decisions/list.html
{% extends "decisions/base.html" %}

{% block title %}Decisions{% endblock %}

{% block content %}
  <div class="container">
    <div class="my-5">
      <p>Found {{ page_obj.paginator.count }} search results for: <span class="fst-italic">{{ q }}</span></p>
      {% if decisions %}
        {% for decision in decisions %}
          <div class="card my-3">
            <div class="card-body">
              <h5 class="card-title">{{ decision.headline|safe }}</h5>
              <p class="card-text">{{ decision.text|truncatechars:50 }}</p>
              <a href="{% url 'decisions:detail' pk=decision.id %}" class="btn btn-outline-primary">Read more</a>
            </div>
            <div class="card-footer fw-lighter">
              Relevancy: {{ decision.rank }}
            </div>
          </div>
        {% endfor %}

        {% if is_paginated %}
          {% include "components/paginator.html" %}
        {% endif %}
      {% else %}
        <p>No decisions found.</p>
      {% endif %}
    </div>
  </div>
{% endblock %}

app/index/templates/index/index.html
{% extends "index/base.html" %}
{% load static %}

{% block title %}BVA Search{% endblock %}

{% block content %}
  <div class="container">
    <div class="px-4 py-5 my-5 text-center">
      <h1 class="display-5 fw-bold text-body-emphasis">Search BVA Decisions</h1>
      <div class="col-lg-6 mx-auto">
        <p class="lead mb-4">Find the information you need to support your claim or win your appeal.</p>
        <div class="">
          <form action="{% url 'decisions:results' %}" method="get" class="" role="search">
            <input type="search" class="form-control rounded-0" placeholder="Search Decisions..." aria-label="Search" name="q">
          </form>
        </div>
      </div>
      {% if not user.is_authenticated %}
      	<div class="mt-3">
          <p><a href="{% url 'account_signup' %}">Create an account</a> to save searches and decisions.</p>
        </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="{% static 'img/favicon.svg' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  {% block extra_head %}{% endblock %}
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  {% include "components/messages.html" %}
  {% include "components/header.html" %}
  <main>{% block content %}{% endblock %}</main>
  {% include "components/footer.html" %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
          crossorigin="anonymous"></script>
  <script src="{% static 'js/main.js' %}"></script>
  {% block extra_body %}{% endblock %}
</body>
</html>

app/templates/components/header.html
<header class="p-3">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center text-decoration-none text-primary">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" fill="currentColor" class="bi bi-file-earmark-text" viewBox="0 0 16 16">
          <path d="M5.5 7a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1zM5 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5m0 2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5"/>
          <path d="M9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.5zm0 1v2A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1z"/>
        </svg>
        <h3>BVA Search</h3>
      </a>
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        {% if user.is_authenticated %}
          <li><a href="#" class="nav-link px-2">Decisions</a></li>
          <li><a href="#" class="nav-link px-2">Searches</a></li>
        {% endif %}
      </ul>
    {% if request.resolver_match.view_name != 'index:index' %}
      <form action="{% url 'decisions:results' %}" method="get" class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
        <input type="search" class="form-control rounded-0" placeholder="Search Decisions..." aria-label="Search" name="q">
      </form>
    {% endif %}
      <div class="text-end">
        <button type="button" class="btn btn-outline-primary me-2 rounded-0">Login</button>
        <button type="button" class="btn btn-secondary rounded-0">Sign-up</button>
      </div>
    </div>
  </div>
</header>

app/templates/components/paginator.html
      <div class="my-3">
          <span>
              {% if page_obj.has_previous %}
                  <a href="?q={{ q }}&page=1">&laquo; first</a>
                  <a href="?q={{ q }}&page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}

              <span class="current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>

              {% if page_obj.has_next %}
                  <a href="?q={{ q }}&page={{ page_obj.next_page_number }}">next</a>
                  <a href="?q={{ q }}&page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
              {% endif %}
          </span>
      </div>